default_platform(:ios)

PROJECT_NAME = ENV["PROJECT_NAME"]

platform :ios do
  lane :build_project do
    cocoapods(clean_install:true)

    build_app(
      workspace: "./FirebaseStarterApp.xcworkspace",
      scheme: "FirebaseStarterApp",
      configuration: "Debug",
      derived_data_path: "output",
      skip_package_ipa: true,
      skip_archive: true,
      xcargs: "ONLY_ACTIVE_ARCH=YES"
    )
  end
end