name: Build Application 🚀🚀

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-application:
    runs-on: [self-hosted, fastlane-swift-ios]
    steps:
      - uses: actions/checkout@v3
      - name: Deintegrate cocoapod
        run: pod deintegrate
      - name: fastlane build application
        run: |
          fastlane build_project
      - name: Archive .app ouput
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: output/Build/Products/Debug-iphonesimulator/FirebaseStarterApp.app